### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by Syenta** [nikkilocke/AccountServer#5]
Hi,

I have been attempting to get Accounting Server up and running but to no avail.

I downloaded and ran the msi file. Once installed I clicked on the icon and received "Error displaying exception:default.tmpl:File not found:'default.inc'".

Your help file didn't make things any clearer so now I'm stuck.

Am I right in assuming that SQLite is installed as part of AccountServer?

If you are able to point me in the right direction so I can get things working I would be grateful.

Regards

Syenta

**Comment by nikkilocke** [comment]
Hi,It looks as if I have forgotten to include a file in the install script. If that is the problem, I will release a new version today to fix the problem.Regards Nikki On 9 Sep 2018 19:56, Syenta <notifications@github.com> wrote:Hi,
I have been attempting to get Accounting Server up and running but to no avail.
I downloaded and ran the msi file. Once installed I clicked on the icon and received "Error displaying exception:default.tmpl:File not found:'default.inc'".
Your help file didn't make things any clearer so now I'm stuck.
Am I right in assuming that SQLite is installed as part of AccountServer?
If you are able to point me in the right direction so I can get things working I would be grateful.
Regards
Syenta

**Comment by nikkilocke** [comment]
Hi Syenta,

I have just uploaded a new release, 1.4.20.

Please download the setup file, and run it - it should fix your problem.

Please let me know how you get on, as I would like to be sure it is working OK for you now.

Thanks,

Nikki

Syenta wrote:
> Hi,
> 
> I have been attempting to get Accounting Server up and running but to no avail.
> 
> I downloaded and ran the msi file. Once installed I clicked on the icon and received "Error displaying exception:default.tmpl:File not found:'default.inc'".
> 
> Your help file didn't make things any clearer so now I'm stuck.
> 
> Am I right in assuming that SQLite is installed as part of AccountServer?
> 
> If you are able to point me in the right direction so I can get things working I would be grateful.
> 
> Regards
> 
> Syenta
> 
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Nikki Locke, Trumphurst Ltd.  PC & Unix consultancy & programming
http://www.trumphurst.com/

**Comment by Syenta** [comment]
You are a genius! The update worked like a dream. Thanks.
