### ISSUE TITLE
Command Prompt Remains Open

### ISSUE THREAD

**Issue by Syenta** [nikkilocke/AccountServer#6]
Hi,

On closing down the browser the Command Prompt remains open.

Is this done on purpose or an issue?

Regards

**Comment by nikkilocke** [comment]
The AccountServer program is a web server, which allows you to connect to it from any computer on your network (subject to your firewall settings). So, once you start it, it keeps running, so you can connect to it.When you run it from the shortcut on your start menu or desktop, it checks to see if it is already running (in which case it doesn't need to start another copy). Then it starts a browser window on your computer connected to the server. Regards Nikki On 13 Sep 2018 5:51 pm, Syenta <notifications@github.com> wrote:Hi,
On closing down the browser the Command Prompt remains open.
Is this done on purpose or an issue?
Regards

**Comment by nikkilocke** [comment]
Closing this issue, as it is working as designed.
